name: blob_flutter
description: A highly customizable and performant 3D particle blob effect for Flutter.
version: 1.0.0
homepage: https://github.com/abod8639/blob_flutter
repository: https://github.com/abod8639/blob_flutter
issue_tracker: https://github.com/abod8639/blob_flutter/issues
topics:
  - 3d
  - animation
  - particles
  - shaders
  - widget

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  shaders:
    - shaders/blob.frag

screenshots:
  - description: "A high-performance interactive 3D particle blob effect."
    path: assets/Picsart.png
