/// Exception hierarchy and diagnostics for BlobFlutter.
///
/// Designed to provide clear, actionable error messages with step-by-step
/// solution hints to help developers quickly resolve configuration, shader,
/// worker, or parameter issues.
library;

/// Base exception class for all errors generated by `blob_flutter`.
class BlobFlutterException implements Exception {
  /// A short summary describing what went wrong.
  final String message;

  /// Additional technical context, such as invalid parameter values or asset paths.
  final String? details;

  /// Concrete, step-by-step instructions for fixing the problem.
  final String? solutionHint;

  /// The underlying exception or error that caused this failure (if any).
  final Object? cause;

  /// The stack trace associated with [cause] (if any).
  final StackTrace? stackTrace;

  /// Creates a [BlobFlutterException].
  const BlobFlutterException({
    required this.message,
    this.details,
    this.solutionHint,
    this.cause,
    this.stackTrace,
  });

  @override
  String toString() {
    final buffer = StringBuffer();
    buffer.writeln();
    buffer.writeln(
        '┌─ [BlobFlutter Exception] ──────────────────────────────────────────────');
    buffer.writeln('│ Message: $message');
    if (details != null && details!.isNotEmpty) {
      buffer.writeln('│ Details: $details');
    }
    if (cause != null) {
      buffer.writeln('│ Underlying Cause: $cause');
    }
    if (solutionHint != null && solutionHint!.isNotEmpty) {
      buffer.writeln('├─ 💡 How to fix:');
      for (final line in solutionHint!.split('\n')) {
        buffer.writeln('│ $line');
      }
    }
    buffer.write(
        '└────────────────────────────────────────────────────────────────────────');
    return buffer.toString();
  }
}

/// Thrown or reported when the GPU fragment shader cannot be loaded or compiled.
class BlobShaderException extends BlobFlutterException {
  /// The asset paths that were attempted when loading the shader.
  final List<String> attemptedPaths;

  const BlobShaderException({
    required super.message,
    this.attemptedPaths = const [],
    super.details,
    super.solutionHint,
    super.cause,
    super.stackTrace,
  });

  /// Factory helper providing standard diagnostics and actionable resolution steps
  /// for missing shader assets.
  factory BlobShaderException.assetLoadFailed({
    required List<String> attemptedPaths,
    Object? cause,
    StackTrace? stackTrace,
  }) {
    return BlobShaderException(
      message: 'Failed to load fragment shader asset for GPU color grading.',
      attemptedPaths: attemptedPaths,
      details: 'Attempted to load shader from paths:\n'
          '${attemptedPaths.map((p) => '  • $p').join('\n')}',
      solutionHint:
          '1. Ensure your pubspec.yaml declares the shader asset under flutter > shaders:\n'
          '     flutter:\n'
          '       shaders:\n'
          '         - packages/blob_flutter/shaders/blob.frag\n'
          '2. Run `flutter pub get` and execute a FULL app restart (Hot Reload is not sufficient for new shaders).\n'
          '3. If running in a test environment, shaders cannot be compiled without custom asset bundles. '
          'BlobFlutter will automatically fallback to CPU point rendering.',
      cause: cause,
      stackTrace: stackTrace,
    );
  }
}

/// Thrown or reported when the background particle computation isolate fails.
class BlobWorkerException extends BlobFlutterException {
  const BlobWorkerException({
    required super.message,
    super.details,
    super.solutionHint,
    super.cause,
    super.stackTrace,
  });

  /// Factory helper for isolate spawn or execution failure.
  factory BlobWorkerException.spawnFailed({
    Object? cause,
    StackTrace? stackTrace,
  }) {
    return BlobWorkerException(
      message:
          'Failed to spawn or communicate with the background particle computation isolate.',
      details:
          'The native worker isolate could not complete its initialization.',
      solutionHint:
          '1. BlobFlutter automatically falls back to main-thread particle math to prevent crashes.\n'
          '2. Check if your platform restricts background isolate spawning (e.g. memory constraints or custom embedders).\n'
          '3. If this occurs on Web, ensure you are using the supported web renderer.',
      cause: cause,
      stackTrace: stackTrace,
    );
  }
}

/// Thrown or asserted when invalid configuration parameters are provided.
class BlobParameterException extends BlobFlutterException {
  /// The parameter name that was invalid.
  final String parameterName;

  /// The invalid value that was provided.
  final dynamic invalidValue;

  /// Creates a [BlobParameterException].
  const BlobParameterException({
    required this.parameterName,
    required this.invalidValue,
    required super.message,
    super.details,
    super.solutionHint,
  });

  /// Factory helper for out-of-range or invalid parameter values.
  factory BlobParameterException.outOfRange({
    required String parameterName,
    required dynamic invalidValue,
    required String validRange,
    String? exampleFix,
  }) {
    return BlobParameterException(
      parameterName: parameterName,
      invalidValue: invalidValue,
      message: "Invalid value for parameter '$parameterName'.",
      details: "Received: $invalidValue. Expected: $validRange.",
      solutionHint: exampleFix != null
          ? 'Provide a valid value within the expected range, e.g.:\n  $exampleFix'
          : 'Provide a valid value matching the criteria: $validRange.',
    );
  }
}
