/// Exception hierarchy and diagnostics for BlobFlutter.
///
/// Designed to provide clear, actionable error messages with step-by-step
/// solution hints to help developers quickly resolve configuration, shader,
/// worker, or parameter issues.
library;

// ── Error Codes ───────────────────────────────────────────────────────────────

/// Categorical code identifying the kind of failure that occurred.
///
/// Enables programmatic handling in [BlobFlutter.onError] without
/// brittle `is`-type checks:
///
/// ```dart
/// BlobFlutter(
///   onError: (error, st) {
///     switch (error.code) {
///       case BlobErrorCode.shaderLoadFailed:
///         // GPU shader unavailable — CPU fallback is already active.
///         break;
///       case BlobErrorCode.workerSpawnFailed:
///         // Isolate couldn't start — computation falls back to main thread.
///         break;
///       default:
///         debugPrint('BlobFlutter error: $error');
///     }
///   },
/// )
/// ```
enum BlobErrorCode {
  /// The GPU fragment shader asset failed to load or compile.
  shaderLoadFailed,

  /// A shader uniform push operation failed at runtime.
  renderFailed,

  /// The background particle computation isolate failed to spawn or communicate.
  workerSpawnFailed,

  /// A compute call to the background worker raised an exception.
  workerComputeFailed,

  /// A parameter value was out of its acceptable range.
  parameterOutOfRange,

  /// Parameters were passed to [BlobFlutter] that conflict with an
  /// attached [BlobController].
  controllerConflict,

  /// An unexpected or unclassified error occurred.
  unknown,
}

// ── Base Exception ────────────────────────────────────────────────────────────

/// Base exception class for all errors generated by `blob_flutter`.
class BlobFlutterException implements Exception {
  /// Categorical code identifying the kind of failure. Use this in
  /// `onError` callbacks for programmatic branching instead of `is` checks.
  BlobErrorCode get code => BlobErrorCode.unknown;

  /// A short summary describing what went wrong.
  final String message;

  /// Additional technical context, such as invalid parameter values or asset paths.
  final String? details;

  /// Concrete, step-by-step instructions for fixing the problem.
  final String? solutionHint;

  /// The underlying exception or error that caused this failure (if any).
  final Object? cause;

  /// The stack trace associated with [cause] (if any).
  final StackTrace? stackTrace;

  /// Creates a [BlobFlutterException].
  const BlobFlutterException({
    required this.message,
    this.details,
    this.solutionHint,
    this.cause,
    this.stackTrace,
  });

  @override
  String toString() {
    final buffer = StringBuffer();
    buffer.writeln();
    buffer.writeln(
        '┌─ [BlobFlutter Exception] ──────────────────────────────────────────────');
    buffer.writeln('│ Code: ${code.name}');
    buffer.writeln('│ Message: $message');
    if (details != null && details!.isNotEmpty) {
      buffer.writeln('│ Details: $details');
    }
    if (cause != null) {
      buffer.writeln('│ Underlying Cause: $cause');
    }
    if (solutionHint != null && solutionHint!.isNotEmpty) {
      buffer.writeln('├─ 💡 How to fix:');
      for (final line in solutionHint!.split('\n')) {
        buffer.writeln('│ $line');
      }
    }
    buffer.write(
        '└────────────────────────────────────────────────────────────────────────');
    return buffer.toString();
  }
}

// ── Shader Exceptions ─────────────────────────────────────────────────────────

/// Thrown or reported when the GPU fragment shader cannot be loaded or compiled.
class BlobShaderException extends BlobFlutterException {
  @override
  BlobErrorCode get code => BlobErrorCode.shaderLoadFailed;

  /// The asset paths that were attempted when loading the shader.
  final List<String> attemptedPaths;

  /// Creates a [BlobShaderException].
  const BlobShaderException({
    required super.message,
    this.attemptedPaths = const [],
    super.details,
    super.solutionHint,
    super.cause,
    super.stackTrace,
  });

  /// Factory helper providing standard diagnostics and actionable resolution steps
  /// for missing shader assets.
  factory BlobShaderException.assetLoadFailed({
    required List<String> attemptedPaths,
    Object? cause,
    StackTrace? stackTrace,
  }) {
    return BlobShaderException(
      message: 'Failed to load fragment shader asset for GPU color grading.',
      attemptedPaths: attemptedPaths,
      details: 'Attempted to load shader from paths:\n'
          '${attemptedPaths.map((p) => '  • $p').join('\n')}',
      solutionHint:
          '1. Ensure your pubspec.yaml declares the shader asset under flutter > shaders:\n'
          '     flutter:\n'
          '       shaders:\n'
          '         - packages/blob_flutter/shaders/blob.frag\n'
          '2. Run `flutter pub get` and execute a FULL app restart (Hot Reload is not sufficient for new shaders).\n'
          '3. If running in a test environment, shaders cannot be compiled without custom asset bundles. '
          'BlobFlutter will automatically fallback to CPU point rendering.',
      cause: cause,
      stackTrace: stackTrace,
    );
  }
}

/// Thrown or reported when a GPU shader uniform push operation fails at runtime.
///
/// This typically occurs if the shader program receives an invalid uniform index
/// or the graphics context is lost. BlobFlutter automatically falls back to CPU
/// point rendering when this error is raised.
class BlobRenderException extends BlobFlutterException {
  @override
  BlobErrorCode get code => BlobErrorCode.renderFailed;

  /// Creates a [BlobRenderException].
  const BlobRenderException({
    required super.message,
    super.details,
    super.solutionHint,
    super.cause,
    super.stackTrace,
  });

  /// Factory helper for shader uniform upload failures.
  factory BlobRenderException.shaderUniformFailed({
    Object? cause,
    StackTrace? stackTrace,
  }) {
    return BlobRenderException(
      message: 'Failed to push uniforms to the GPU fragment shader.',
      details: cause?.toString(),
      solutionHint:
          '1. BlobFlutter has automatically disabled GPU rendering and fallen back to CPU point rendering.\n'
          '2. This can happen if the graphics context is lost (e.g., app backgrounded on some devices).\n'
          '3. A full app restart will re-initialise the shader pipeline.',
      cause: cause,
      stackTrace: stackTrace,
    );
  }
}

// ── Worker Exception ──────────────────────────────────────────────────────────

/// Thrown or reported when the background particle computation isolate fails.
class BlobWorkerException extends BlobFlutterException {
  @override
  BlobErrorCode get code => BlobErrorCode.workerSpawnFailed;

  /// Creates a [BlobWorkerException].
  const BlobWorkerException({
    required super.message,
    super.details,
    super.solutionHint,
    super.cause,
    super.stackTrace,
  });

  /// Factory helper for isolate spawn or initialization failure.
  factory BlobWorkerException.spawnFailed({
    Object? cause,
    StackTrace? stackTrace,
  }) {
    return BlobWorkerException(
      message:
          'Failed to spawn or communicate with the background particle computation isolate.',
      details:
          'The native worker isolate could not complete its initialization.',
      solutionHint:
          '1. BlobFlutter automatically falls back to main-thread particle math to prevent crashes.\n'
          '2. Check if your platform restricts background isolate spawning (e.g. memory constraints or custom embedders).\n'
          '3. If this occurs on Web, ensure you are using the supported web renderer.',
      cause: cause,
      stackTrace: stackTrace,
    );
  }

  /// Factory helper for errors that occur during an active compute call.
  factory BlobWorkerException.computeFailed({
    Object? cause,
    StackTrace? stackTrace,
  }) {
    return _BlobWorkerComputeException(
      message: 'An error occurred during background particle computation.',
      details: cause?.toString(),
      solutionHint:
          '1. BlobFlutter will continue rendering using cached particle positions.\n'
          '2. If this recurs, check for memory pressure or isolate restrictions on your platform.',
      cause: cause,
      stackTrace: stackTrace,
    );
  }
}

/// Internal subclass so `computeFailed` can have its own `code`.
class _BlobWorkerComputeException extends BlobWorkerException {
  @override
  BlobErrorCode get code => BlobErrorCode.workerComputeFailed;

  const _BlobWorkerComputeException({
    required super.message,
    super.details,
    super.solutionHint,
    super.cause,
    super.stackTrace,
  });
}

// ── Parameter Exception ───────────────────────────────────────────────────────

/// Thrown or asserted when invalid configuration parameters are provided.
class BlobParameterException extends BlobFlutterException {
  @override
  BlobErrorCode get code => BlobErrorCode.parameterOutOfRange;

  /// The parameter name that was invalid.
  final String parameterName;

  /// The invalid value that was provided.
  final dynamic invalidValue;

  /// Creates a [BlobParameterException].
  const BlobParameterException({
    required this.parameterName,
    required this.invalidValue,
    required super.message,
    super.details,
    super.solutionHint,
  });

  /// Factory helper for out-of-range or invalid parameter values.
  factory BlobParameterException.outOfRange({
    required String parameterName,
    required dynamic invalidValue,
    required String validRange,
    String? exampleFix,
  }) {
    return BlobParameterException(
      parameterName: parameterName,
      invalidValue: invalidValue,
      message: "Invalid value for parameter '$parameterName'.",
      details: "Received: $invalidValue. Expected: $validRange.",
      solutionHint: exampleFix != null
          ? 'Provide a valid value within the expected range, e.g.:\n  $exampleFix'
          : 'Provide a valid value matching the criteria: $validRange.',
    );
  }
}

// ── Controller Conflict Exception ─────────────────────────────────────────────

/// Thrown or asserted when conflicting parameters are passed to [BlobFlutter]
/// alongside an external [BlobController].
///
/// When a [BlobController] is attached, all geometric, physics, and visual
/// parameters must be configured directly on the controller, because widget-level
/// parameters are ignored.
class BlobControllerConflictException extends BlobFlutterException {
  @override
  BlobErrorCode get code => BlobErrorCode.controllerConflict;

  /// The names of the conflicting parameters passed to [BlobFlutter].
  final List<String> conflictingParameters;

  /// Creates a [BlobControllerConflictException].
  const BlobControllerConflictException({
    required this.conflictingParameters,
    required super.message,
    super.details,
    super.solutionHint,
  });

  /// Factory helper providing clear, non-distracting diagnostics and resolution steps.
  factory BlobControllerConflictException.fromParameters(
    List<String> conflictingParameters,
  ) {
    final paramList = conflictingParameters.map((p) => "'$p'").join(', ');
    return BlobControllerConflictException(
      conflictingParameters: conflictingParameters,
      message:
          'Settings passed to BlobFlutter ($paramList) are IGNORED because [controller] is attached.',
      details:
          'When [controller] is provided, all physics and appearance properties must be configured '
          'directly on the BlobController instance. Parameters passed to BlobFlutter have no effect.',
      solutionHint:
          '1. Configure these properties directly on the controller:\n'
          '     final controller = BlobController(\n'
          '${conflictingParameters.map((p) => '       $p: ...,').join('\n')}\n'
          '     );\n'
          '2. Remove ($paramList) from BlobFlutter.',
    );
  }

  @override
  String toString() {
    final paramList = conflictingParameters.map((p) => "'$p'").join(', ');
    final buffer = StringBuffer();
    buffer.writeln(
        'BlobControllerConflictException: Settings passed to BlobFlutter ($paramList) are IGNORED because [controller] is attached.');
    buffer.writeln('All properties outside the controller have no effect.');
    buffer.writeln();
    buffer.writeln('Fix:');
    buffer.writeln('  1. Move them into BlobController:');
    buffer.writeln('       final controller = BlobController(');
    for (final p in conflictingParameters) {
      buffer.writeln('         $p: ...,');
    }
    buffer.writeln('       );');
    buffer.write('  2. Remove ($paramList) from BlobFlutter(...).');
    return buffer.toString();
  }
}
